server:
  port: 6001
eureka:
  instance:
    hostname: 127.0.0.1:6001
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://127.0.0.1:6002/eureka/
  server:
    enable-self-preservation: false